spring.application.name=devcollab
spring.mongodb.uri=mongodb://localhost:27017/devcollab
server.port=8080

jwt.secret=devcollab-secret-key-make-this-very-long-and-secure-in-production
jwt.expiration=86400000